pipeline {
    agent any
    environment {
        REGISTRY = "docker.io"
        IMAGE_NAME = "krishloga9318/flask-pg-backend"
        IMAGE_TAG = "latest"
        K8S_REPO = 'https://gitlab.com/loganathan-dhavel/flask-pg-backend-argocd.git'
        K8S_BRANCH = "main"
    }

    stages {
        stage('checkout scm') {
            steps {
              checkout scm
            }
        }

        stage('Check dirs') {
            steps {
                sh "ls -lrth"
            }
        }

        stage('Build docker image') {
            steps {
                sh "docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./docker/Dockerfile ."
            }
        }

        stage('Push to docker registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                    echo $PASS | docker login -u $USER --password-stdin $REGISTRY
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    """
                }
            }
        }

        stage('Push K8s Manifests to GitLab') {
            steps {
                    sh """
                    mkdir k8s-repo
                    git clone $K8S_REPO k8s-repo
                    cp -r ./k8s/* k8s-repo/
                    cd k8s-repo
                    git add .
                    git commit -m "Update manifests for image $IMAGE_NAME:$IMAGE_TAG"
                    git push origin $K8S_BRANCH
                    """
            }
        }
    }
}
